### ISSUE TITLE
Add web UI

### ISSUE THREAD

**Issue by k0pernicus** [SOMCA/hot-pepper#2]
A web UI can be usefull to visualize in real time the energy consumption of the device

**Comment by rouvoy** [comment]
I would advice you to use the following combo:
- [InfluxDB Docker container](https://hub.docker.com/r/tutum/influxdb)
- [Grafana Docker container](https://hub.docker.com/r/grafana/grafana)
- [InfluxDB Python client](https://github.com/influxdata/influxdb-python)

Grafana will offer you nice [web dashboards](http://grafana.org/features).
Deploying Docker containers is rather straightforward.

**Comment by k0pernicus** [comment]
Awesome!
Thank you for this advice ;-)

**Comment by MehdiAit** [comment]
Thank you @rouvoy !!
